TodoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('todo/', include('todo_app.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='todo_app/login.html')),
    path('admin/', admin.site.urls),
]

todo_app/urls.py
from django.urls import path
from . import views

app_name = "todo_app"
urlpatterns = [
                path('all/', views.TaskListView.as_view(), name='index'),
                path('add/', views.TaskCreateView.as_view(), name='add_task'),
                path('<int:pk>', views.TaskUpdateView.as_view(), name='update_task'),
                path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
                path('<int:pk>/done/', views.TaskDeleteView.as_view(), name='completed_task'),
                path('search/<q>', views.TaskSearchView.as_view(), name='search_task'),

                path('api/tasks', views.task_list),
                path('api/tasks/<int:pk>', views.task_detail),
                ]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime as dt


def is_task_overdue(sch_date):
    days_overdue = (dt.today().date() - sch_date).days
    is_overdue = days_overdue > 0
    return is_overdue, days_overdue


class Tag(models.Model):

    COLORS = (('yellow', 'Yellow'), ('orange', 'Orange'),
              ('red', 'Red'), ('green', 'Green'),
              ('purple', 'Purple'), ('blue', 'Blue'))

    name = models.CharField(max_length=15)
    color = models.CharField(choices=COLORS, max_length=10, default='yellow')

    def __str__(self):
        return self.name


class Task(models.Model):

    IMP_CHOICES = (('normal', 'Normal'),
                   ('medium', 'Medium'),
                   ('critical', 'Critical'))

    title = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    schedule_date = models.DateField(default=dt.today().date() + timedelta(days=1))
    is_done = models.BooleanField(default=False)
    is_overdue = models.BooleanField(default=False)
    days_overdue = models.IntegerField(default=0)
    importance = models.CharField(choices=IMP_CHOICES, max_length=10, default='normal')
    managed_by = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ["is_done", "-schedule_date"]

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        res = is_task_overdue(self.schedule_date)
        self.is_overdue = res[0]
        self.days_overdue = res[1]
        return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

todo_app/forms.py
from django.forms import ModelForm, Textarea, DateInput, CheckboxSelectMultiple
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'schedule_date', 'importance', 'managed_by', 'tags', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 20, 'rows': 2, 'placeholder': 'Add details'}),
            'schedule_date': DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
            'tags': CheckboxSelectMultiple()
        }
        help_texts = {
            'schedule_date': "When you are planning to achieve this task",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for vf in self.visible_fields():
            vf.field.widget.attrs['class'] = 'rounded px-2 py-1 w-2/3'
            if vf.field.label == 'Comment':
                vf.field.widget.attrs['class'] += ' placeholder-gray-800'

todo_app/views.py
from django.utils import decorators
from django.contrib.auth.decorators import login_required
from django.views import generic
from .models import Task
from .forms import TaskForm

from django.http.response import JsonResponse
from rest_framework import status
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view
from .serializers import TaskSerializer


class TaskListView(generic.ListView):
    template_name = 'todo_app/list_task.html'
    context_object_name = 'all_tasks'

    # use: model or queryset or get_queryset
    def get_queryset(self):
        return Task.objects.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_tasks'] = len(context_data['all_tasks'])
        return context_data


class TaskCreateView(generic.edit.CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'todo_app/add_task.html'
    success_url = "/todo/all"


class TaskUpdateView(generic.edit.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'todo_app/update_task.html'
    success_url = "/todo/all"


class TaskDeleteView(generic.edit.DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = "/todo/all"

    @decorators.method_decorator(login_required)
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class TaskSearchView(TaskListView):

    def get_queryset(self):
        return Task.objects.filter(title__icontains=self.request.GET[self.kwargs['q']])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['query'] = self.request.GET[self.kwargs['q']]
        return context_data


#   **************************  api views   **************************


@api_view(['GET', 'POST', 'DELETE'])
def task_list(request):
    if request.method == 'GET':
        tasks = Task.objects.all()
        title = request.GET.get('title', None)
        if title is not None:
            tasks = tasks.filter(title__icontains=title)
        tasks_serializer = TaskSerializer(tasks, many=True)
        return JsonResponse(tasks_serializer.data, safe=False)
    elif request.method == 'POST':
        task_data = JSONParser().parse(request)
        task_serializer = TaskSerializer(data=task_data)
        if task_serializer.is_valid():
            task_serializer.save()
            return JsonResponse(task_serializer.data, status=status.HTTP_201_CREATED)
        return JsonResponse(task_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        count = Task.objects.all().delete()
        return JsonResponse({'message': '{} Tasks were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'PUT', 'DELETE'])
def task_detail(request, pk):
    try:
        task = Task.objects.get(pk=pk)
    except Task.DoesNotExist:
        return JsonResponse({'message': 'The task does not exist'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        task_serializer = TaskSerializer(task)
        return JsonResponse(task_serializer.data)
    elif request.method == 'PUT':
        task_data = JSONParser().parse(request)
        task_serializer = TaskSerializer(task, data=task_data)
        if task_serializer.is_valid():
            task_serializer.save()
            return JsonResponse(task_serializer.data)
        return JsonResponse(task_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        task.delete()
        return JsonResponse({'message': 'Task was deleted successfully!'}, status=status.HTTP_204_NO_CONTENT)

todo_app/templates/todo_app/add_task.html
{% extends "todo_app/base.html" %}

{% block title %}New Task{% endblock %}

{% block container %}

    <div class="flex justify-center">
        <div class="w-1/2">
            <p class="self-end text-blue-300 uppercase font-thin">Register a new task</p>
            <form method="post" class="mt-5 space-y-2 flex flex-col">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex justify-between">
                        <label for="{{ field.id_for_label }}" class="uppercase font-thin text-md text-gray-300">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" value="SAVE"
                       class="w-2/3 p-1 self-end rounded-lg bg-indigo-700 text-gray-200 cursor-pointer border border-blue-600 shadow-lg hover:border-blue-500">
            </form>
        </div>
    </div>

{% endblock %}

todo_app/templates/todo_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="{% static 'todo_app/img/favicon.png' %}">
        <link href="https://unpkg.com/tailwindcss@^1/dist/tailwind.min.css" rel="stylesheet">
        <script type="text/javascript" src="{% static 'todo_app/js/base.js' %}"></script>
        <title>
            {% block title %}Manage Your TODOs Here{% endblock %}
        </title>
    </head>
    <body class="w-full max-w-screen-xl mx-auto px-24 mt-5 bg-indigo-900">

        <div id="header" class="flex flex-grow rounded bg-indigo-800 shadow-lg">
            <div class="px-2 self-center text-gray-400 text-3xl hover:shadow-lg hover:text-gray-200">
                <a href="{% url 'todo_app:index' %}">TODOs</a>
            </div>
            <div class="w-full p-2">
                {% block search_form %}{% endblock %}
            </div>
            <div id="date-area" class="w-1/6 p-2 self-center text-right text-teal-300">{% now "DATE_FORMAT" %}</div>
        </div>

        <div id="container" class="mt-20 px-8 pb-8 shadow-lg rounded-lg">
            {% block container %}
            {% endblock %}
        </div>

        <footer id="footer">
        </footer>

    </body>
</html>

todo_app/templates/todo_app/edit_task.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Manage Your TODOs Here</title>
    </head>

    <body>
        <div id="header">
        </div>

        <div id="container">
            {% if task %}
                <h1>{{ task.title }}</h1>
                <form action="{% url "todo_app:index" %}" method="post">
                    {% csrf_token %}
                    <input id="id" type="hidden" name="id" value="{{ task.id }}">
                    <br>
                    <label for="title">Title</label>
                    <input id="title" type="text" name="title" value="{{ task.title }}">
                    <br>
                    <label for="comment">Comment</label>
                    <input id="comment" type="text" name="comment" value="{{ task.comment }}">
                    <br>
                    <label for="schedule_date">Scheduled For</label>
                    <input id="schedule_date" type="date" name="schedule_date" value="{{ task.schedule_date }}">
                    <br>
                    <input type="submit" value="Save">
                </form>
            {% else %}
                <p>No corresponding task was found.</p>
            {% endif %}
        </div>

        <div id="footer">
        </div>
    </body>
</html>

todo_app/templates/todo_app/list_task.html
{% extends "todo_app/base.html" %}
{% load static %}

{% block search_form %}
    <form method="get" action="{% url 'todo_app:search_task' 'q' %}" class="flex justify-center">
        {% csrf_token %}
        <input type="text" name="q" value="{{ query }}" placeholder="Ex: Work out"
               class="w-1/2 px-2 py-1 rounded-lg bg-gray-200 text-gray-800 placeholder-gray-800
                      text-center shadow-lg focus:bg-gray-100">
        <input type="submit" value="FIND"
               class="px-2 ml-2 rounded-lg cursor-pointer bg-indigo-700 text-teal-200 border border-blue-600 shadow-lg hover:border-blue-500">
    </form>
{% endblock %}


{% block container %}

    <div class="flex justify-between">
        <span class="self-end font-thin text-md text-blue-300 uppercase">
            {% if count_tasks %}
                {{ count_tasks }} Task{{ count_tasks|pluralize }}
            {% else %}
                No tasks found
            {% endif %}
        </span>
        <div class="self-end w-3/4">
            <span class="mx-2 text-md text-blue-300">Today's</span>
            <span class="mx-2 text-md text-blue-300">Overdue</span>
            <span class="mx-2 text-md text-blue-300">Completed</span>
        </div>
        <a href="{% url "todo_app:add_task" %}" class="shadow-lg hover:bg-indigo-800 rounded-full p-1">
            <img src="{% static 'todo_app/img/add.png' %}" class="max-w-xs h-8" title="Add new task">
        </a>
    </div>
    <div class="mt-3">
        {% if all_tasks %}
            <table class="table-auto w-full shadow-inner">
                <thead class="text-blue-300 font-semibold uppercase shadow-inner">
                    <tr class="text-center py-2">
                        <td class="w-1/5">Title</td>
                        <td class="w-1/5">Scheduled For</td>
                        <td class="w-1/6">Importance</td>
                        <td class="w-1/6">Managed by</td>
                        <td class="w-1/6">Tags</td>
                        <td class="w-1/6">Overdue</td>
                        <td class=""></td>
                    <tr>
                </thead>
                <tbody class="bg-indigo-700 text-gray-300 shadow-lg">
                    {% for task in all_tasks %}
                        <tr id="table-row-{{ forloop.counter }}"
{#                            onmouseleave="hide_mark_done({{ forloop.counter }})" onmouseover="display_mark_done({{ forloop.counter }})"#}
                            class="space-x-4 text-center shadow-inner {% if forloop.counter|divisibleby:2 %}bg-indigo-600{% endif %}">
                            <td class="p-1" title="{{ task.title }}">{{ task.title|slice:":22"}}{% if task.title|length > 22 %}...{% endif %}</td>
                            <td class="p-1">{{ task.schedule_date }}</td>
                            <td class="p-1">{{ task.importance|title }}</td>
                            <td class="p-1">{{ task.managed_by }}</td>
                            <td class="p-1">{% for t in task.tags.all %}
                                                <span class="rounded px-1 bg-{{ t.color }}-600 text-black text-xs shadow-md
                                                             border border-indigo-800">{{ t }}</span>
                                            {% endfor %}
                            </td>
                            <td class="p-1">
                                <div id="actions_dropdown_neighbor-{{ forloop.counter }}"
                                     class="dropdown-neighbor {% if task.is_overdue %}text-red-500{% endif %}">
                                    {% if task.is_overdue %}
                                        {{ task.days_overdue }} Day{{ task.days_overdue|pluralize }} ago
                                    {% else %}
                                        Not yet
                                    {% endif %}
                                </div>
                                <div id="actions_dropdown-{{ forloop.counter }}"
                                     class="dropdown-panel flex justify-center shadow rounded-full p-px hidden">
                                    <a href="{% url "todo_app:update_task" task.id %}" class="hover:bg-gray-500 rounded-full p-px">
                                        <img src="{% static 'todo_app/img/edit.png'%}" class="max-w-xs h-4" title="Edit Task">
                                    </a>
                                    <a href="{% url "todo_app:delete_task" task.id %}" class="ml-2 hover:bg-gray-500 rounded-full p-px">
                                        <img src="{% static 'todo_app/img/delete.png'%}" class="max-w-xs h-4" title="Delete Task">
                                    </a>
                                    <a href="{% url "todo_app:completed_task" task.id %}" class="ml-2 hover:bg-gray-500 rounded-full p-px">
                                        <img src="{% static 'todo_app/img/checkmark.png' %}" class="max-w-xs h-4" title="Mark as completed">
                                    </a>
                                </div>
                            </td>
                            <td class="p-1">
                                <div id="actions_dropdown_btn" class="px-1 font-bold cursor-pointer hover:bg-indigo-800 rounded" title="Actions"
                                     onclick="show_actions({{ forloop.counter }})">⋮</div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

{% endblock %}

todo_app/templates/todo_app/login.html
{% extends "todo_app/base.html" %}

{% block title %}Login to continue{% endblock %}

{% block container %}

    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

todo_app/templates/todo_app/task_confirm_delete.html
{% extends "todo_app/base.html" %}

{% block title %}Delete Task{% endblock %}

{% block container %}

    <form method="post">
        {% csrf_token %}
        <p class="mb-4 p-2 rounded self-end bg-indigo-200 text-red-700 uppercase font-thin">
            Confirm to delete this task: <span class="font-bold text-black underline">{{ task }}</span>
        </p>
        <input type="submit" value="Yes, Delete"
               class="uppercase p-1 rounded-lg bg-indigo-700 text-gray-200 cursor-pointer border border-blue-600 shadow-lg hover:border-blue-500">
    </form>

{% endblock %}

todo_app/templates/todo_app/update_task.html
{% extends "todo_app/base.html" %}

{% block title %}Update Task{% endblock %}

{% block container %}

    <div class="flex justify-center">
        <div class="w-1/2">
            <p class="self-end text-blue-300 uppercase font-thin">Update task</p>
            <form method="post" class="mt-5 space-y-2 flex flex-col">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex justify-between">
                        <label for="{{ field.id_for_label }}" class="uppercase font-thin text-md text-gray-300">{{ field.label }}</label>
                        {% if field.label == 'Tags' %}
{#                            {% for t in field.area.all %}{{ area }}<br/>{% endfor %}#}
                            {{ field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    </div>
                {% endfor %}
                <input type="submit" value="UPDATE"
                       class="w-2/3 p-1 self-end rounded-lg bg-indigo-700 text-gray-200 cursor-pointer border border-blue-600 shadow-lg hover:border-blue-500">
            </form>
        </div>
    </div>

{% endblock %}